// This file was auto-generated by ML.NET Model Builder.

using Microsoft.ML;

namespace TheBestWebInterface.ML
{
    public partial class SCLER
    {
        /// <summary>
        /// model input class for SCLER.
        /// </summary>


        /// <summary>
        /// model output class for SCLER.
        /// </summary>
        #region model output class


        #endregion

        private static string MLNetModelPath = Path.GetFullPath("ML/SCLER.mlnet");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);


        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

    }
}
